service: elasticbeanstalk-deployer


provider:
  name: aws
  runtime: nodejs6.10
  profile: test-user

# you can overwrite defaults here
  stage: prod
  region: eu-central-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "arn:aws:logs:*:*:*"
    - Effect: "Allow"
      Action:
        - "elasticbeanstalk:DescribeApplicationVersions"
        - "elasticbeanstalk:DescribeEnvironments"
        - "elasticbeanstalk:UpdateEnvironment"
      Resource: "arn:aws:elasticbeanstalk:::*"
    - Effect: "Allow"
      Action:
        - "cloudformation:GetTemplate"
      Resource: "arn:aws:cloudformation:::*"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
        - "s3:GetObjectVersion"
      Resource: "arn:aws:s3:::elasticbeanstalk-*"
    - Effect: "Allow"
      Action:
        - "codepipeline:PutJobFailureResult"
        - "codepipeline:PutJobSuccessResult"
      Resource: "*"


functions:
  deploy:
    handler: handler.deploy

